### ISSUE TITLE
Custom Field - Meta Description

### ISSUE THREAD

**Issue by royashgit** [sybrew/the-seo-framework#593] opened 2021-11-11 10:37 UTC
Hello,

I have been using this function to make the metafield description take the value of a custom field. However, this no longer works. Any help please?

```
add_filter( 'the_seo_framework_custom_field_description', function( $description, $args ) {

	if ( $description )
		return $description;

	if ( function_exists( 'get_field' ) ) {
		// Pass ID for SEO bar compatibility.
		$excerpt = get_field( 'fl_description', $args['id'], false ) ?: '';

		if ( $excerpt ) {

			$description = the_seo_framework()->trim_excerpt( $excerpt, mb_strlen( $excerpt ), 155 );
		}
	}

	return $description;
}, 10, 2 );
```

**Comment by sybrew** [comment] 2021-11-11 15:04
Duplicate of https://wordpress.org/support/topic/custom-field-meta-description/.

Please don't double post. I'll get to you there as soon as I can.

**Closed by sybrew** 2021-11-11 15:04 UTC
