### ISSUE TITLE
Enhance Social media opengraph image output for pages/posts without featured images

### ISSUE THREAD

**Issue by lifeforceinst** [sybrew/the-seo-framework#341] opened 2018-08-01 16:58 UTC
This is an enhancement request to improve the output of opengraph image metadata in additional instances so that a more rich SEO can be achieved. **On pages or posts which do not have a featured image, it is desirable to still produce open graph image metadata if possible.**  This will also help many plugins which rely on the opengraph data to add images when sharing or posting to social media.

**If the page or post contains a featured image:** When the SEO Framework is set to output Opengraph data for Social Media, the plugin correctly sets the opengraph metadata `<meta property=og:image" content="url-of-image.jpg">`.

**If the page or post does not contains a featured image:**  When the SEO Framework is set to output Opengraph data for Social Media, the plugin sets the opengraph metadata `<meta property=og:image" content="">` if no Social Image Fallback URL is set.

Some other SEO solutions check the post or page and _if there is no featured image, they will check the post or page content for an embedded image._ If the post or page contains an embedded image then this will be added to the metadata.

It would be great if we could have such an enhancement as this is the only thing which I have found missing compared to many of the big players int he SEO plugin world.

**Comment by sybrew** [comment] 2018-08-02 11:25
Thank you so much for your feedback!

I'm going to see whether I can remove the empty output, 
I'm not sure why I forced that [two years ago](https://theseoframework.com/changelog/2-1-1-image/).

I've pushed your suggestion to v3.2, and I'll consider implementing it for v3.1 if it's easier than expected.

Closing as duplicate of #268

Tip: You can set a "Social Image Fallback URL" via the SEO Settings, under "Social Meta Settings'" General tab.

**Closed by sybrew** 2018-08-02 11:25 UTC

**Comment by lifeforceinst** [comment] 2018-08-02 13:56
As per comment on other issue #268.  You also need to consider that the URL from a post could be absolute or relative URL - remember the golden rule of programming is not to assume.

Here is an example of how I retrieved images in one of my themes, which determines if there is a featured image, if not, then tried to extract image from post using preg_match and if no image can then apply a default image (such as the fallback image if set).

 $thumbnail    = wp_get_attachment_image_src (get_post_thumbnail_id( $post->ID), 'thumbnail');
   if (empty($thumbnail)) {
    // There is no featured image, so check for embedded image
    $theimage = preg_match_all('/<img.+src=[\'"]([^\'"]+)[\'"].*>/i', $post->post_content, $matches);
    $firstimg = $matches[1][0];
    if (empty($firstimg)) {
      $thumbnail = array ('0' => $the_fallback_image);
    } else {
      // Need to handle relative or absolute image URI, by using parse_url to get the image path
     // Then add this to the home URI
      $fileimg  = parse_url ($firstimg, PHP_URL_PATH);
      $firsturl = home_url() . $fileimg;
      $thumbnail = array ('0' => $firsturl);
    }

**Comment by lifeforceinst** [comment] 2018-08-02 14:07
FYI,
I recently implement a similar function for one of my themes.
     $thumbnail    =
wp_get_attachment_image_src (get_post_thumbnail_id( $post->ID),
'thumbnail');
       if (empty($thumbnail)) {
        // There is no featured image,
so check for embedded image
        $theimage =
preg_match_all('/<img.+src=[\'"]([^\'"]+)[\'"].*>/i',
$post->post_content, $matches);
        $firstimg =
$matches[1][0];
        if (empty($firstimg)) {
          $thumbnail = array
('0' =>
'
https://thelifeforceinstitute.com/images/logo300.jpg');
        } else {
          // Need to check
is if image name includes sitename and protocol
          $fileimg  =
parse_url ($firstimg, PHP_URL_PATH);
          $firsturl =
home_url() . $fileimg;
          $thumbnail = array
('0' => $firsturl);
       
}      
  }

At 12:25 02/08/2018, Sybre Waaijer wrote:
Thank you so much for your
feedback!
I'm going to see whether I can remove the empty output,
I'm not sure why I forced that
two years
ago.
I've pushed your suggestion to v3.2, and I'll consider implementing it
for v3.1 if it's easier than expected.
Closing as duplicate of
#268

Tip: You can set a "Social Image Fallback URL" via the SEO
Settings, under "Social Meta Settings'" General tab.
­
You are receiving this because you authored the thread.
Reply to this email directly,

view it on GitHub, or

mute the thread.

The Life Force
Institute 
illuminating your
life
London United Kingdom |
Barcelona Spain | Brisbane Australia 
Web:
thelifeforceinstitute.com
and www.tlfi.com.au
eMail:

thelifeforceinstitute@gmail.com
On receiving and access this
material, you accept our terms and conditions, which are available at

thelifeforceinstitute.com/home/terms.
