### ISSUE TITLE
Hide Breadcrumbs for specific taxonomies

### ISSUE THREAD

**Issue by SimeonGriggs** [sybrew/the-seo-framework#267] opened 2018-02-21 07:09 UTC
I know the Breadcrumbs Schema can be disabled entirely with...

`add_filter( 'the_seo_framework_json_breadcrumb_output', '__return_false' );` 

...but is it possible to filter this to just specific taxonomies?

**Comment by sybrew** [comment] 2018-02-21 10:00
Hi @SimeonGriggs 

This is possible using a function.
See [has_category()](https://developer.wordpress.org/reference/functions/has_category/) to adjust the outcome.

```php
add_filter( 'the_seo_framework_json_breadcrumb_output', function( $output = true ) {
	// (int|string|array) (Required) Category ID, name or slug, or array of said.
	$terms = array();

	if ( has_category( $terms ) ) {
		$output = false;
	}

	return $output;
} );

**Comment by SimeonGriggs** [comment] 2018-02-21 21:03
Cool thanks. Is it possible though to just filter out a specific category from the breadcrumbs? This code removes all categories, and I can't see a filter that would allow this.

**Comment by sybrew** [comment] 2018-02-21 21:37
Hi @SimeonGriggs 

Do you mean that this:
`Home > Category > Sub Category > Page`

Becomes this?
`Home > Sub Category > Page`

You can adjust this behavior using the primary category selection tool. 
This is done via the radio button found next to each selected category:
![image](https://user-images.githubusercontent.com/7662236/36506655-8b6019b6-1757-11e8-8a07-9c123a71cd95.png)

If this isn't what you meant, could you give me an example of "what I have... and what I want"?

**Comment by SimeonGriggs** [comment] 2018-02-21 22:06
It's actually a WooCommerce product which has two Product Categories assigned to it, but the Breadcrumb being produced is for one I'd rather hide. So `has_term` would be what I'm hoping to use, something like...

`if ( has_term( $terms, 'product_cat' ) ) {`

...but instead of removing the Breadcrumbs entirely, just skipping them if they match this `$term`.

**Comment by SimeonGriggs** [comment] 2018-02-21 22:06
It's actually a WooCommerce product which has two Product Categories assigned to it, but the Breadcrumb being produced is for one I'd rather hide. So has_term would be what I'm hoping to use, something like...

if ( has_term( $terms, 'product_cat' ) ) {

...but instead of removing the Breadcrumbs entirely, just skipping them if they match this $term.

**Comment by sybrew** [comment] 2018-02-22 10:44
Hi Simeon,

I do see those primary term selection radio boxes next to the category selections on product pages:
![image](https://user-images.githubusercontent.com/7662236/36533886-3a7ba678-17c5-11e8-9bd3-599840a6330b.png)

When they're not listed as parent/child categories, just set the one you wish to have highlighted in Google Search as primary and it should work.

I'm hasting through the 3.0.4 release because of an incorrect assessment, so I have little time to inspect any custom code 😅. If you are unable to get it working by next week I'll take a closer look.

**Comment by SimeonGriggs** [comment] 2018-02-23 02:35
Ooooh just realised I wasn't on the latest version of the plugin. Sorry. Okay so I'm seeing those radio buttons now.

...would be nice to globally disable a Taxonomy from ever being used as a Breadcrumb but I understand I'm an edgy edge case.

**Comment by sybrew** [comment] 2018-02-23 13:14
Hi Simeon,

I'm glad you've found them 😄 
Do those buttons resolve the initial issue?

For exclusion of taxonomies, the `the_seo_framework_ld_json_breadcrumb_terms` filter would then be helpful. When only the excluded taxonomies are assigned to the post/CPT, the breadcrumbs won't render.

But usage thereof is indeed "edgy edge" 😉.

**Comment by SimeonGriggs** [comment] 2018-02-25 22:34
Yeah the Primary Category worked, thanks. And I'll look more into that filter to make it permanent.

**Comment by sybrew** [comment] 2018-02-25 23:59
I'm glad it works as intended 😄 Have a great Monday!

**Closed by sybrew** 2018-02-25 23:59 UTC
Labels: Support
