### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by koreos** [sybrew/the-seo-framework#390] opened 2018-12-08 14:07 UTC
Please add breadcrumbs with basic settings like in Yoast.

**Comment by sybrew** [comment] 2018-12-12 16:44
TSF delivers rich data breadcrumbs, which are used in Google. That's all an SEO plugin should do.

However, there are plans to move this to the front-end. For that, I'm closing this duplicate of #276

**Closed by sybrew** 2018-12-12 16:44 UTC
