### ISSUE TITLE
None of my sites are indexed, except the starting site

### ISSUE THREAD

**Issue by chrischtili** [sybrew/the-seo-framework#607] opened 2022-05-13 04:24 UTC
When I go to Google Search Console and check my site, only the main page ( https://360grad.art) is crawled and indexed. The others are not. 
I added one manually ( https://360grad.art/was-ist-ein-virtueller-rundgang/ ). But adding the sites manually can be a lot of work.

As is wrote in another thread here, monitor says: The robots.txt file is not handled by The SEO Framework.

**Comment by sybrew** [comment] 2022-05-15 17:10
Mostly a duplicate of https://wordpress.org/support/topic/sites-are-not-crawled-and-indexed-by-google/; answered there.

https://360grad.art/was-ist-ein-virtueller-rundgang/ is indexed, and I couldn't find a blocker:
![image](https://user-images.githubusercontent.com/7662236/168484993-742e7ba0-5109-4ed7-95a1-53e3a64f57f6.png)

_Aside: The FAQ Schema.org from Kadence seems to be working well; one of the reasons why #456 is being pushed back by me._

Since your inquiry seems resolved already, I'm closing this issue. Feel free to let me know if you're still finding issues; I still get notifications if you reply.

**Closed by sybrew** 2022-05-15 17:10 UTC
Labels: [Type] Support

**Comment by chrischtili** [comment] 2022-05-15 19:45
Hey Sybrew,
thanks for your research. I have meanwhile manually indexed all my pages (well, there are not so many) from Google.
