### ISSUE TITLE
Can we actually pull in and edit meta titles and descriptions instead of have them grayed out?

### ISSUE THREAD

**Issue by asianmusicguy** [sybrew/the-seo-framework#306] opened 2018-05-06 19:53 UTC
Right now we see a faded example but the actual box is blank to fill in a custom one but often times  we only need to make a few small tweaks so i find myself having to retyple whole text boxes when all i might want to do is remove a single word for example

**Comment by sybrew** [comment] 2020-02-19 14:40
Closing as duplicate of #27.

**Closed by sybrew** 2020-02-19 14:40 UTC
Labels: [Resolution] Duplicate
