### ISSUE TITLE
Title too long when it's not

### ISSUE THREAD

**Issue by htmlplus43** [sybrew/the-seo-framework#1] opened 2016-02-14 06:25 UTC
I have a small WooCommerce store. At the time of this issue submission I have 81 categories. Some of the categories I use the generated title and some I create a custom title because of the length. The issue is SEO framework says the title is too long for the custom titles I created when they are between 50 - 55 characters. This doesn't happen on all of the custom titles only some.

**Comment by sybrew** [comment] 2016-02-14 06:55
Hi htmlplus43,

This is a known bug and it was the cause for me to refactor the code.
This should be resolved as of 2.6.0 (next update).

Keep an eye out on the dev branch to see the progression. Stay tuned!

**Comment by htmlplus43** [comment] 2016-02-14 08:17
OK I will update as soon as it becomes available. Thank you so much for creating this great plugin. Keep up the great work.

Have a great day.
Rod

**Comment by sybrew** [comment] 2016-03-07 08:42
Thanks Rod!

It seems to be fixed in the current Alpha (I can't pinpoint at what stage as so much has been refactored) :).

Everything uses the same functions now for generating titles, instead of splitting the admin and front-end. Much more maintainable, but all this took me a good while.

All known bugs are fixed :) (except for one rare & odd one that I still need to test).

Feel free to try it out, and if so please let me know if you find anything :).

**Comment by htmlplus43** [comment] 2016-03-07 10:10
OK is it an upgrade from within Wordpress admin?

I will check it out.

Thank you for the reply. Great plugin great work you are doing we greatly appreciate it.

**Comment by sybrew** [comment] 2016-03-07 12:47
Hi Rod,

Anytime :)

It's still in Alpha, you can get it here: https://github.com/sybrew/the-seo-framework/tree/alpha
Please note that the transients are disabled for debugging, so things will feel a lot slower.

Currently live testing this on my network :). Haven't found any issues as of yet!

A lot more features are still to be added. And if anything does feel off, you can update it back to 2.5.2.2 through the Plugin activation screen.

**Closed** 2016-03-07 13:12 UTC
Labels: bug
