### ISSUE TITLE
Custom Taxonomy isn't Listed in Sitemap

### ISSUE THREAD

**Issue by black-eye** [sybrew/the-seo-framework#391] opened 2018-12-09 16:14 UTC
Are custom taxonomies supposed be listen in the sitemap?
Because mine isn't.

I have a custom taxonomy shared by 2 CPT's. Both CPT's are listed in the Sitemap, but taxonomy isn't.
Both CPT's and taxonomy are public and queryable, indexing is allowed etc.

Am I doing something wrong, or is it a feature?
Thanks

**Comment by sybrew** [comment] 2018-12-12 20:32
Nope, they're not supposed to be in the sitemap. I've excluded taxonomies for [many reasons](https://kb.theseoframework.com/?p=21).

However, I've just added a filter entry that implements this feature for you:
https://theseoframework.com/docs/api/filters/#sitemap-related

Closing as a duplicate of #31

**Closed by sybrew** 2018-12-12 20:32 UTC
Labels: [Resolution] Duplicate
