### ISSUE TITLE
Breadcrumb not generated correctly

### ISSUE THREAD

**Issue by paulka007** [sybrew/the-seo-framework#358] opened 2018-09-12 10:17 UTC
Hi folks. I could be wrong but I seem to be getting errors on my breadcrumb data according to the Structured data testing tool:

https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fdogonline.co.za%2Fp%2Fdog-life-jacket%2F
![image](https://user-images.githubusercontent.com/16636353/45419696-50128a80-b688-11e8-81d2-e03ba758cb60.png)

I think the last item is missing the product page url in the "@id" tag. When I manually added it in the testing tool it worked:
![image](https://user-images.githubusercontent.com/16636353/45418832-d4174300-b685-11e8-9692-bfc7677a07df.png)

Also there are two breadcrumb listing in the testing tool any idea why? Disabling  TSF breadcrumb option only makes one of them disappear:
![image](https://user-images.githubusercontent.com/16636353/45419044-70414a00-b686-11e8-81c6-5aad1c76e719.png)

**Comment by sybrew** [comment] 2018-09-12 10:50
The first error is from The SEO Framework, the second is from WooCommerce.

In v3.1. both will be fixed. The release of which is scheduled this weekend.

Duplicate of The SEO Framework: #347 
Duplicate of WooCommerce: https://github.com/woocommerce/woocommerce/issues/21152

**Closed by sybrew** 2018-09-12 10:50 UTC
