### ISSUE TITLE
Disable SEO for specific post types

### ISSUE THREAD

**Issue by michaelezra** [sybrew/the-seo-framework#343] opened 2018-08-08 18:21 UTC
Is there a way to disable SEO entirely for specific post types?
For example, PICU collections (www.hostname.com/collections/1234)

Many thanks!

**Comment by sybrew** [comment] 2018-08-09 02:29
Duplicate of #112 

Will be shipped with v3.1 😄

**Closed by sybrew** 2018-08-09 02:29 UTC

**Comment by michaelezra** [comment] 2018-08-12 16:06
great, thank you!
