### ISSUE TITLE
HREFLANG Tag

### ISSUE THREAD

**Issue by MartyD23** [sybrew/the-seo-framework#338] opened 2018-07-23 16:35 UTC
Hi, It would be good if you could add an option to set HREFLANG Tag globally for all posts in the sitemap. Thanks

**Comment by sybrew** [comment] 2018-07-24 00:17
Seems like a duplicate of #69

Translation plugins already take care of this in the header. So the tag isn't necessary in the sitemap.

If you're not using translation plugins, then feel free to reopen this and elaborate. Thanks!

**Closed by sybrew** 2018-07-24 00:17 UTC

**Comment by MartyD23** [comment] 2018-07-24 00:40
I'm not using a translation plugin. 

This came to my attention after seeing Google Webmaster Tools which said my site doesn't have any HREFLANG tags.

Looking around i saw one option to include this would be in the sitemap.

Is it necessary to include such tags for an English language only site?

**Comment by MartyD23** [comment] 2018-07-24 16:54
Hi Sybrew,

My site language in the Wordpress settings has always been set to English (United States).

I just checked my theme and in my header i have <html lang="en-US"> which is at the very top and starts before the head tag as such:

`<!DOCTYPE html>




<html lang="en-US">

<head>`

Should i perhaps move the `<html lang>` tag so that it starts within the `<head>` tag?

The current setup is unchanged from how the developers created the theme.

Thanks

**Comment by sybrew** [comment] 2018-07-24 19:54
That looks good to me, the "lang" attribute is correctly added, as it should have been.
The IE6~8 support hurts my head, however: nobody uses that anymore.

You shouldn't change it. What you see there are conditional opening tags, in the only acceptable order.

_P.S. To use code blocks, you need to use three ticks: ` ``` `
With optional tags, like "html" added to it, for styling: ` ```html`_
